project:
  type: website
  output-dir: docs

website:
  title: "Visual Analytics Project"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: Proposal.qmd
        text: "Proposal"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true