project:
  type: website
  output-dir: docs

website:
  title: "Visual Analytics Project"
  navbar:
    background: "#3155E7"
    foreground: "#ffffff"
    search: true

    left:
      - icon: file-earmark-text
        href: Proposal.qmd
        text: "Proposal"

      - icon: diagram-3
        text: "Methodology"
        menu:
          - text: "Data Prepartion"
            href: "Methodology/Data Preparation.qmd"
          - text: "Data Prepartion_Test"
            href: "Methodology/Data Preparation_Test.qmd"
          
      - icon: card-list
        href: Findings.qmd
        text: "Findings"

      - icon: file-earmark-ppt
        href: Poster.qmd
        text: "Poster"

      - icon: journal-text
        text: "Meeting Minutes"
        menu:
          - text: "Meeting Minutes 1"
            href: "Meeting Minutes/Meeting_Minutes_Day1.qmd"
          - text: "Meeting Minutes 2"
            href: "Meeting Minutes/Meeting_Minutes_Day2.qmd"

    right:
      - icon: people-fill
        href: The_Team.qmd
        text: "The Team"

      - icon: laptop
        text: "Shiny App"
        menu:
          - text: "Launch Shiny App"
            href: "https://your-shiny-app-link-here"

      - icon: github
        text: "Github"
        menu:
          - text: "GitHub Repository"
            href: "https://github.com/RstudioMichelle/VisualAnalyticsGroupProject-AJM-"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true