---
title: "Meeting Minutes"
date: "22 June, 2026"
date-modified: "last-modified"
format: html
execute:
  eval: true
  echo: true
  warning: false
  freeze: false
---

## Time: 4:30pm

## In Attendance

-   Alvin Ong

-   Javier Phang

-   Michelle Chen

## **Agenda**

1.  Go through previous action items 
2.  Discussion on project next steps 
3.  Next meetup and objective 

## **Discussion on proposal**

1. Javier initiated the meeting by referencing our seniors work on Shiny App and mention that there he has created a methodology section on our website by combining the steps.  

2. Javier also mentions that there is unfamiliarity with Shiny app, which we all agreed. 

3. Alvin and Javier agree that the static graphs should be on the poster while interactivity is crucial on the shiny app. 

4. The team agreed that our Take-Home Exercise 2 had too many static charts, and this made it difficult to port it to the Shiny App. 

5. Javier also highlighted the Shiny App portion takes up 50% of our total marks, while the poster is somewhere at 10 - 15%. 

6. While going through our seniors work on shiny app, Michelle asked if we need to follow the examples given by using a network chart and bar chart, but the team thinks that our dataset is different and we are free to explore. 

7. We went through each other's take home exercise 2 charts and explore what existing work can we leverage on. 

8. The team also aligned on the wireframing of the shiny app based on the senior’s work. 

9. The team started discussing on Q1, where Alvin showed what he attempted for Q1, but the result is not the best at answering the question. Alvin later suggested using a Chord Diagram + a text analytics chart such as TD-IDF as the next steps and the team agreed. Thereafter, a wireframe for Q1 was drawn for reference. 

10. For Q2, the team wanted to use Alvin’s and Michelle existing network chart to visualise for the question. Michelle also suggested using her heatmap, but Alvin and Javier do not agree that it answers the question as it depends on static keywords and does not show a pre and post scenarios. But the team agreed that the 2 networks should be sufficient and a good kick-off for Javier to experiment on Shiny App. A wireframe for Q2 was then drawn for reference. 

 

11. Javier also mentioned that he thinks 2 network charts might be too confusing for the audience. Alvin than suggested using a panel-tabset and the team agreed to try it out.  

 

12. For Q3, we once again revisited each of our take home exercise, but there isn’t any network graph that we can put into the shiny app. There were 2 relevant bar charts that need to be modified, but more work will have to be done to answer the question. Hence, a wireframe for Q3 was drawn for reference. 

 

13. Michelle volunteered to do Q3 to evenly split out the work and the team agreed. She also mentions her incoming commitments and aligned with the team on what are our current deadlines and schedules 

 

14. Javier also mentioned about discussing about the poster, but we do not have anything concrete to discuss further, hence this discussion is postponed to Monday, 22nd June at 8pm. 

 

15. The team has also set up another meeting on Wednesday, 24th June at 10pm to discuss on the Shiny App and our current updates. 

## Questions to ask Prof Kam during consultation

No question asked at this point

## Action items

1. Brainstorm on the Poster 

2. Alvin to continue working on Q1 

3. Javier to work on Q2 

4. Michelle to work on Q3 

5. Next Poster Meeting is tomorrow at 8pm 

6. Next Shiny App meeting is on 24th June on progress and shiny app. 

## Meeting Minutes Sign off

| No. | Name          | Sign off |
|-----|---------------|----------|
| 1   | Alvin Ong     | Yes      |
| 2   | Javier Phang  | Yes      |
| 3   | Michelle Chen | Yes      |
